name: Esporta PDF
on:
  push:
    branches:
      - nightlys
  pull_request_target:
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: npm install
      - run: node esporta.js
      - name: Archive PDF
        uses: actions/upload-artifact@v3
        with:
          name: cheatsheet
          path: cheatsheet.pdf 
      - name: Create prerelease
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly Release"
          files: cheatsheet.pdf
